services:
  db:
    image: 'postgres:13.1'
    container_name: db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - CLIENT_ID=${AUTH_CLIENT_ID}
    ports:
      - "${BACKEND_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_AUTH_CLIENT_ID=${VITE_AUTH_CLIENT_ID}
        - VITE_SECURE_LOCAL_STORAGE_HASH_KEY=${VITE_SECURE_LOCAL_STORAGE_HASH_KEY}
        - VITE_SECURE_LOCAL_STORAGE_PREFIX=${VITE_SECURE_LOCAL_STORAGE_PREFIX}
    volumes:
      - "./frontend/src/:/usr/app/src/"
      - "./frontend/build:/usr/app/build/"
      - "./frontend/public/:/usr/app/public/"
      - "./frontend/cypress/:/usr/app/cypress/"
      -  "./certbot/www:/var/www/certbot/:ro"
    ports:
      - "${FRONTEND_PORT}:5173"
    env_file:
      - .env
  certbot:
    image: certbot/certbot:v2.8.0
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
