package com.zpi.backend.email;

public enum EmailType {
    REGISTRATION, RESERVATION_ACCEPTED, RESERVATION_REJECTED, RESERVATION_PENDING,
    RESERVATION_COMING_SOON, RESERVATION_CANCELED_BY_OWNER,  RESERVATION_CANCELED_BY_RENTER,
    RESERVATION_FINISHED, RESERVATION_TODAY, RESERVATION_EXPIRED
}
