openapi: 3.0.1
info:
  title: GameShare App
  version: "1.0"
servers:
- url: /
  description: localhost
security:
- Token Authorization: []
paths: {}
components:
  securitySchemes:
    Token Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
