insert into public.categories (id, name)
values  (1, 'Economic'),
        (2, 'Industry / Manufacturing'),
        (3, 'Post-Napoleonic'),
        (4, 'Trains'),
        (5, 'Transportation'),
        (6, 'Environmental'),
        (7, 'Medical'),
        (8, 'Adventure'),
        (9, 'Exploration'),
        (10, 'Fantasy'),
        (11, 'Fighting'),
        (12, 'Miniatures'),
        (13, 'Animals'),
        (528, 'Aviation / Flight'),
        (16, 'Civilization'),
        (19, 'Negotiation'),
        (20, 'Political'),
        (21, 'Science Fiction'),
        (22, 'Space Exploration'),
        (23, 'Wargame'),
        (234, 'Racing'),
        (235, 'Sports'),
        (29, 'Territory Building'),
        (30, 'Movies / TV / Radio theme'),
        (31, 'Novel-based'),
        (160, 'Spies/Secret Agents'),
        (163, 'Comic Book / Strip'),
        (914, 'Age of Reason'),
        (45, 'Civil War'),
        (322, 'Prehistoric'),
        (550, 'Number'),
        (53, 'Mythology'),
        (328, 'Deduction'),
        (258, 'Video Game Theme'),
        (61, 'Card Game'),
        (64, 'Modern Warfare'),
        (263, 'Mature / Adult'),
        (67, 'American West'),
        (266, 'Bluffing'),
        (561, 'World War II'),
        (74, 'Dice'),
        (75, 'Medieval'),
        (77, 'Ancient'),
        (79, 'City Building'),
        (275, 'Abstract Strategy'),
        (277, 'Renaissance'),
        (196, 'Action / Dexterity'),
        (648, 'Pike and Shot'),
        (92, 'Horror'),
        (741, 'World War I'),
        (97, 'Nautical'),
        (99, 'Farming'),
        (102, 'Puzzle'),
        (359, 'Party Game'),
        (295, 'Arabian'),
        (108, 'Educational'),
        (361, 'Word Game'),
        (218, 'Murder/Mystery'),
        (115, 'Collectible Components'),
        (222, 'Pirates'),
        (122, 'Travel'),
        (128, 'Religious'),
        (677, 'Zombies'),
        (775, 'Humor'),
        (693, 'Real-time'),
        (778, 'Print & Play')
        ON CONFLICT DO NOTHING;
ALTER SEQUENCE categories_seq RESTART WITH 1000;