name: CICD

on:
  pull_request:
    branches:
      - develop
    types: 
      - opened
      - closed
      - synchronize

jobs:
  cd:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      checks: write
      issues: read
      pull-requests: write
    
    env:
      BACKEND_HOST: ${{ secrets.BACKEND_HOST }}
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}

      FRONTEND_HOST: ${{ secrets.FRONTEND_HOST }}
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
      AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}

      SECURE_LOCAL_STORAGE_HASH_KEY: ${{ secrets.SECURE_LOCAL_STORAGE_HASH_KEY }}
      SECURE_LOCAL_STORAGE_PREFIX: ${{ secrets.SECURE_LOCAL_STORAGE_PREFIX }}

      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      VITE_AUTH_CLIENT_ID: ${{ secrets.VITE_AUTH_CLIENT_ID }}
      VITE_SECURE_LOCAL_STORAGE_HASH_KEY: ${{ secrets.VITE_SECURE_LOCAL_STORAGE_HASH_KEY }}
      VITE_SECURE_LOCAL_STORAGE_PREFIX: ${{ secrets.VITE_SECURE_LOCAL_STORAGE_PREFIX }}

      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

      GCP_CONFIG_FILE: ${{ secrets.GCP_CONFIG_FILE }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_BUCKET_ID: ${{ secrets.GCP_BUCKET_ID }}
      GCP_DIR_NAME: ${{ secrets.GCP_DIR_NAME }}

      ADMIN1_EMAIL: ${{ secrets.ADMIN1_EMAIL }}
      ADMIN2_EMAIL: ${{ secrets.ADMIN2_EMAIL }}
      ADMIN3_EMAIL: ${{ secrets.ADMIN3_EMAIL }}
      ADMIN4_EMAIL: ${{ secrets.ADMIN4_EMAIL }}


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v1'
        with: 
          credentials_json: ${{ secrets.IAC_CICD_SA }}

      - name: Deploy GCE
        run: | 
          gcloud compute instances create app-${{ GITHUB_SHA }} --machine-type=e2-highmem-2  --project=zpi-test-1 --zone=us-east4-a \
          --metadata=startup-script='
            #!/bin/bash
            sudo apt-get -y update
            sudo apt-get -y install ca-certificates curl gnupg
            sudo install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            sudo chmod a+r /etc/apt/keyrings/docker.gpg

            echo \
              "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
              "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
              sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

            sudo apt-get -y update
            sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            sudo apt-get -y install git
            git clone https://github.com/zpi-project/gameshare-app.git
            touch gameshare-app/.env
            touch gameshare-app/backend/src/main/resources/gcp-account-file.json

            echo ${{secrets.IAC_CICD_SA}} > gameshare-app/backend/src/main/resources/gcp-account-file.json

            echo ADMIN1_EMAIL=${{secrets.ADMIN1_EMAIL}} >> gameshare-app/.env
            echo ADMIN2_EMAIL=${{secrets.ADMIN2_EMAIL}} >> gameshare-app/.env
            echo ADMIN3_EMAIL=${{secrets.ADMIN3_EMAIL}} >> gameshare-app/.env
            echo ADMIN4_EMAIL=${{secrets.ADMIN4_EMAIL}} >> gameshare-app/.env
            echo AUTH_CLIENT_ID="${{secrets.AUTH_CLIENT_ID}}" >> gameshare-app/.env
            echo BACKEND_HOST="${{secrets.BACKEND_HOST}}" >> gameshare-app/.env
            echo BACKEND_PORT="${{secrets.BACKEND_PORT}}" >> gameshare-app/.env
            echo CLIENT_ID="${{secrets.CLIENT_ID}}" >> gameshare-app/.env
            echo DB_HOST="${{secrets.DB_HOST}}" >> gameshare-app/.env
            echo DB_NAME="${{secrets.DB_NAME}}" >> gameshare-app/.env
            echo DB_PASSWORD="${{secrets.DB_PASSWORD}}" >> gameshare-app/.env
            echo DB_PORT="${{secrets.DB_PORT}}" >> gameshare-app/.env
            echo DB_USER="${{secrets.DB_USER}}" >> gameshare-app/.env
            echo FRONTEND_HOST="${{secrets.FRONTEND_HOST}}" >> gameshare-app/.env
            echo FRONTEND_PORT="${{secrets.FRONTEND_PORT}}" >> gameshare-app/.env
            echo GCP_BUCKET_ID="${{secrets.GCP_BUCKET_ID}}" >> gameshare-app/.env
            echo GCP_CONFIG_FILE="${{secrets.GCP_CONFIG_FILE}}" >> gameshare-app/.env
            echo GCP_DIR_NAME="${{secrets.GCP_DIR_NAME}}" >> gameshare-app/.env
            echo GCP_PROJECT_ID="${{secrets.GCP_PROJECT_ID}}" >> gameshare-app/.env
            echo SECURE_LOCAL_STORAGE_HASH_KEY="${{secrets.SECURE_LOCAL_STORAGE_HASH_KEY}}">> gameshare-app/.env
            echo SECURE_LOCAL_STORAGE_PREFIX="${{secrets.SECURE_LOCAL_STORAGE_PREFIX}}" >> gameshare-app/.env
            echo VITE_API_URL="${{secrets.VITE_API_URL}}" >> gameshare-app/.env
            echo VITE_AUTH_CLIENT_ID=${{secrets.VITE_AUTH_CLIENT_ID}} >> gameshare-app/.env
            echo VITE_SECURE_LOCAL_STORAGE_HASH_KEY=${{secrets.VITE_SECURE_LOCAL_STORAGE_HASH_KEY}} >> gameshare-app/.env
            echo VITE_SECURE_LOCAL_STORAGE_PREFIX=${{secrets.VITE_SECURE_LOCAL_STORAGE_PREFIX}} >> gameshare-app/.env

            cd gameshare-app
            sudo docker compose up'
