name: NPM-CloudRun CICD

on:
  pull_request:
    branches:
      - develop
    types: 
      - opened
      - closed
      - synchronize

jobs:
  npm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      checks: write
      issues: read
      pull-request: write
    env:
      WORKING_DIR: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v1'
        with: 
          credentials_json: ${{ secrets.IAC_CICD_SA }}
      
      - name: Login to Artifact registry
        uses: docker/login-action@v3
        with:
          registry: europe-central2-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.IAC_CICD_SA }}

      - name: Build Docker image
        run: |
          docker build ${{ env.WORKING_DIR }} -t app

      - name: Push Docker image to Artifact Registry
        run: |
          docker tag app europe-central2-docker.pkg.dev/zpi-test-1/docker-repository-zpi/frontend
          docker push europe-central2-docker.pkg.dev/zpi-test-1/docker-repository-zpi/frontend
